version: '3'
services:

  app:
    build: 
      context: ./app
      dockerfile: Dockerfile  # Use the main Dockerfile for the application
    ports:
      - "8000:8000"  # Map the application port
    volumes:
      - ./app:/app  # Mount code from ./backend into the container
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile.tests  # Create a new Dockerfile for running tests
    command: ["pytest", "/tests"]  # Run pytest for your tests

